# Generated by Django 4.1.2 on 2023-01-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tangkap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koordinat', models.CharField(max_length=100)),
                ('gambar', models.FileField(null=True, upload_to='map/')),
                ('jenistangkapan', models.CharField(max_length=100)),
                ('harga', models.CharField(max_length=100)),
                ('jenis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tangkap_app.jenis')),
            ],
        ),
        migrations.CreateModel(
            name='Nelayan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.FileField(null=True, upload_to='nelayan/')),
                ('nama', models.CharField(max_length=100)),
                ('tipe', models.CharField(max_length=100)),
                ('tentang', models.TextField()),
                ('usaha_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tangkap_app.usaha')),
            ],
        ),
    ]
